version: '3'

services:
  backend:
    build: TripMateBackend
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://tripmatedb:3306/tripmate?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: 12345678
    restart: always
    depends_on:
      tripmatedb:
          condition: service_healthy
  tripmatedb:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: tripmate
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10